name: Publish package

on:
  push:
    tags:
      - 'v*' # Push events to matching  i.e. v1.0.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Extract Version
      run: | 
        TAG=${{ github.ref }}
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo "VERSION=${TAG#refs/tags/v}" >> $GITHUB_ENV

    # - name: Build and pack 
    #   working-directory: src/Openbus.AzureServiceBus
    #   run: |
    #     dotnet build --configuration Release --version-suffix=$VERSION
    #     dotnet pack --configuration Release --output ./nuget --version-suffix=$VERSION

    # - name: Publish NuGet packages
    #   working-directory: src/Openbus.AzureServiceBus/nuget
    #   run: dotnet nuget push Openbus.AzureServiceBus.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
